FROM jinseob2kim/docker-rshiny:latest



# For OHDSI
RUN R -e "remotes::install_github(c('ohdsi/SqlRender', 'ohdsi/DatabaseConnector', 'ohdsi/OhdsiSharing', 'ohdsi/FeatureExtraction', 'ohdsi/CohortMethod', 'ohdsi/EmpiricalCalibration', 'ohdsi/MethodEvaluation', 'ohdsi/Andromeda', 'ohdsi/ParallelLogger', 'ohdsi/Cyclops', 'ohdsi/OhdsiRTools','ohdsi/CohortDiagnostics', 'ohdsi/ROhdsiWebApi','ohdsi/PatientLevelPrediction'))" 









